name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
      spanner-emulator:
        image: gcr.io/cloud-spanner-emulator/emulator
        ports:
          - 9010:9010
          - 9020:9020
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Configure git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.1'

      - name: Setup NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check NPM token validity
        run: |
          if ! npm token list >/dev/null 2>&1; then
            echo "NPM token is invalid or has expired"
            exit 1
          fi
      
      - name: Install root package
        run: |
          npm i
      
      - name: Build packages
        run: |
          npm run build-workspace

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Configure gcloud for Spanner Emulator
        run: |
          gcloud config configurations create emulator || gcloud config configurations activate emulator
          gcloud config set auth/disable_credentials true
          gcloud config set project proteinjs-test
          gcloud config set api_endpoint_overrides/spanner http://localhost:9020/

      - name: Create Spanner Instance
        run: |
          gcloud spanner instances create proteinjs-test --config=emulator-config --description="Protein JS Test Instance" --nodes=1

      - name: Create Spanner Database
        run: |
          gcloud spanner databases create test --instance=proteinjs-test

      - name: Test packages
        env:
          SPANNER_EMULATOR_HOST: localhost:9020
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_DATABASE: test
        run: |
          npm run test-workspace

      - name: Commit package-locks
        run: |
          git add .
          if git diff --staged --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "chore(version) update package-locks [skip ci]"
            git fetch origin main
            git rebase origin/main
            git push origin main
          fi

      - name: Version and Publish
        run: |
          npx lerna publish --yes --no-private
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
